### PR TITLE
Fix downloads from subfolders

### PR DESCRIPTION
**Pull request by WHITE-developer**

### CODE REVIEW

**Comment by WHITE-developer** [comment]
@kennethormandy ?

**Comment by kennethormandy** [comment]
Hey, thanks for this PR. I’ll make sure it gets merged (or #4, which I think overlaps with this). I was the one that added this functionality in the plugin on Craft 2, but I guess I didn’t properly port that part to Craft 3. So I’d also like to get the [tests I have on a branch](https://github.com/kennethormandy/craft-s3securedownloads/tree/ko-test-asset) finished, so that this can be consistently tested.

**Comment by WHITE-developer** [comment]
@kennethormandy It's been a while, do you have any progress?

**Comment by kennethormandy** [comment]
Hey thanks for the PR, this is merged and checked with tests now.

The next version will have this change. You can give it a try now with:

```sh
composer require kennethormandy/craft-s3securedownloads:3.0.0-beta.1
```

**Pull request merged**
